NAME      = iroffer$(VERSION)
INSDIR    = /usr/local/bin

IROFFER_OBJECTS = \
	obj/autosend.o \
	obj/conversions.o \
	obj/iroffer_admin.o \
	obj/iroffer_dccchat.o \
	obj/iroffer_display.o \
	obj/iroffer_main.o \
	obj/iroffer_md5.o \
	obj/iroffer_misc.o \
	obj/iroffer_statefile.o \
	obj/iroffer_transfer.o \
	obj/iroffer_upload.o \
	obj/iroffer_utilities.o \
	obj/parsing.o

HEADERS   = \
	src/autosend.h \
	src/conversions.h \
	src/iroffer_config.h \
	src/iroffer_defines.h \
	src/iroffer_globals.h \
	src/iroffer_headers.h \
	src/iroffer_md5.h \
	src/parsing.h \
	Makefile

TARED_BASE = \
	$(NAME)/sample.config \
	$(NAME)/README \
	$(NAME)/LICENSE \
	$(NAME)/CHANGELOG.md

TARED_SRC = \
	$(NAME)/src/*.c \
	$(NAME)/src/*.h \
	$(NAME)/Makefile.config \
	$(NAME)/Configure \
	$(NAME)/tools/iroffer.cron \
	$(NAME)/tools/dynip.sh

OBJDIR = obj/.mkdir

LDLIBS    = $(CONFIG_LDLIBS)
LDFLAGS   = $(CONFIG_LDFLAGS)
CFLAGS    = $(CONFIG_CFLAGS)
CPPFLAGS  = -Isrc $(CONFIG_CPPFLAGS)

all: iroffer $(CONFIG_TARGETS)

iroffer: $(OBJDIR) $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) -o iroffer

iroffer_chroot: $(OBJDIR) $(IROFFER_OBJECTS)
	$(CC) $(LDFLAGS) $(IROFFER_OBJECTS) $(LOADLIBES) $(LDLIBS) $(CONFIG_CHROOT) -o iroffer_chroot

src-doc:
	mkdir -p srcdocs
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) src/*.c src/*.h
	cxref -block-comments -index-all -xref-all -Osrcdocs \
		-Niroffer $(CPPFLAGS) -html20 src/*.c src/*.h

$(OBJDIR):
	mkdir -p obj
	touch $(OBJDIR)

obj/irofferall.o: $(OBJDIR) $(IROFFER_OBJECTS)
	$(LD) -r -o obj/irofferall.o $(IROFFER_OBJECTS)

obj/autosend.o: src/autosend.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/autosend.o src/autosend.c
obj/conversions.o: src/conversions.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/conversions.o src/conversions.c
obj/iroffer_admin.o: src/iroffer_admin.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_admin.o src/iroffer_admin.c
obj/iroffer_dccchat.o: src/iroffer_dccchat.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_dccchat.o src/iroffer_dccchat.c
obj/iroffer_display.o: src/iroffer_display.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_display.o src/iroffer_display.c
obj/iroffer_main.o: src/iroffer_main.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_main.o src/iroffer_main.c
obj/iroffer_md5.o: src/iroffer_md5.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_md5.o src/iroffer_md5.c
obj/iroffer_misc.o: src/iroffer_misc.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_misc.o src/iroffer_misc.c
obj/iroffer_statefile.o: src/iroffer_statefile.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_statefile.o src/iroffer_statefile.c
obj/iroffer_transfer.o: src/iroffer_transfer.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_transfer.o src/iroffer_transfer.c
obj/iroffer_upload.o: src/iroffer_upload.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_upload.o src/iroffer_upload.c
obj/iroffer_utilities.o: src/iroffer_utilities.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/iroffer_utilities.o src/iroffer_utilities.c
obj/parsing.o: src/parsing.c $(HEADERS) $(OBJDIR)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o obj/parsing.o src/parsing.c

tar: clean
	touch * src/*
	cd ..; tar -cf $(NAME)/$(NAME).tar $(TARED_BASE) $(TARED_SRC)
	gzip $(NAME).tar
	mv $(NAME).tar.gz $(NAME).tgz

clean:
	rm -rf iroffer iroffer_chroot core obj src/*~ *~

install: all
	install -o root -g root -m 0755 iroffer $(INSDIR)/iroffer

# end
